using NestNet.Infra.BaseClasses;
using NestNet.Infra.Attributes;

namespace SampleApp.Modules.MyModules.Entities
{
    [Entity("MyModules")]
    public class MyModule : EntityBase
    {
        // This property enables code at 'NestNet.Infra' to handle the entity in general 
        // manner (without knowing the specific name 'MyModuleId').
        [Prop(
            create: GenOpt.Ignore,
            update: GenOpt.Ignore,
            result: GenOpt.Ignore,
            store: DbOpt.Ignore
        )]
        public override int Id
        {
            get { return MyModuleId; }
            set { MyModuleId = value; }
        }

        // Value of this property is auto generated by the DB.
        [Prop(
            create: GenOpt.Ignore,
            update: GenOpt.Ignore,
            result: GenOpt.Mandatory,
            store: DbOpt.PrimaryKey
        )]
        public int MyModuleId { get; set; }

        [Prop(
            create: GenOpt.Mandatory,
            update: GenOpt.Optional,
            result: GenOpt.Mandatory,
            store: DbOpt.Standard
        )]
        public required string Name { get; set; }

        [Prop(
            create: GenOpt.Mandatory,
            update: GenOpt.Optional,
            result: GenOpt.Mandatory,
            store: DbOpt.Standard
        )]
        public int Age { get; set; }

        [Prop(
            create: GenOpt.Optional,
            update: GenOpt.Optional,
            result: GenOpt.Optional,
            store: DbOpt.Standard
        )]
        public string? Email { get; set; }

        [Prop(
            create: GenOpt.Mandatory,
            update: GenOpt.Ignore,
            result: GenOpt.Ignore,
            store: DbOpt.Ignore
        )]
        public string? MyVirtualField { get; set; }
    }
}