using NestNet.Infra.BaseClasses;
using NestNet.Infra.Attributes;
using System.ComponentModel.DataAnnotations.Schema;

namespace SampleApp.Modules.MyModules.Entities
{
    [Table("MyModules")]
    public class MyModule : EntityBase
    {
        // This property enables code at 'NestNet.Infra' to handle the entity in general 
        // manner (without knowing the specific name 'MyModuleId').
        [Prop(
            create: GenOpt.Ignore,
            update: GenOpt.Ignore,
            result: GenOpt.Ignore
        )]
        // DB - ignore
        public override long Id
        {
            get { return MyModuleId; }
            set { MyModuleId = value; }
        }

        // Value of this property is auto generated by the DB.
        [Prop(
            create: GenOpt.Ignore,
            update: GenOpt.Ignore,
            result: GenOpt.Mandatory
        )]
        // DB - pk
        public long MyModuleId { get; set; }

        [Prop(
            create: GenOpt.Mandatory,
            update: GenOpt.Optional,
            result: GenOpt.Mandatory
        )]
        // DB - standard
        public required string Name { get; set; }

        [Prop(
            create: GenOpt.Mandatory,
            update: GenOpt.Optional,
            result: GenOpt.Mandatory
        )]
        // DB - standard
        public long Age { get; set; }

        [Prop(
            create: GenOpt.Optional,
            update: GenOpt.Optional,
            result: GenOpt.Optional
        )]

        // DB - standard
        public string? Email { get; set; }

        [Prop(
            create: GenOpt.Mandatory,
            update: GenOpt.Ignore,
            result: GenOpt.Ignore
        )]
        // DB - ignore
        public string? MyVirtualField { get; set; }
    }
}