# Get environment variables
Write-Host "Environment variables set:"
Write-Host "MSSQL_SERVER: $([Environment]::GetEnvironmentVariable('MSSQL_SERVER', 'User'))"
Write-Host "MSSQL_DB_NAME: $([Environment]::GetEnvironmentVariable('MSSQL_DB_NAME', 'User'))"
Write-Host "MSSQL_USER: $([Environment]::GetEnvironmentVariable('MSSQL_USER', 'User'))"
Write-Host "MSSQL_PASSWORD: $([Environment]::GetEnvironmentVariable('MSSQL_PASSWORD', 'User'))"
Write-Host "MSSQL_TRUST_SERVER_CERTIFICATE: $([Environment]::GetEnvironmentVariable('MSSQL_TRUST_SERVER_CERTIFICATE', 'User'))"
Write-Host "MSSQL_TRUSTED_CONNECTION: $([Environment]::GetEnvironmentVariable('MSSQL_TRUSTED_CONNECTION', 'User'))"
Write-Host "MSSQL_MULTIPLE_ACTIVE_RESULT_SETS: $([Environment]::GetEnvironmentVariable('MSSQL_MULTIPLE_ACTIVE_RESULT_SETS', 'User'))"