# Get environment variables
Write-Host "Environment variables set:"
Write-Host "DB_SERVER: $([Environment]::GetEnvironmentVariable('DB_SERVER', 'User'))"
Write-Host "DB_NAME: $([Environment]::GetEnvironmentVariable('DB_NAME', 'User'))"
Write-Host "DB_USER: $([Environment]::GetEnvironmentVariable('DB_USER', 'User'))"
Write-Host "DB_PASSWORD: $([Environment]::GetEnvironmentVariable('DB_PASSWORD', 'User'))"
Write-Host "DB_TRUST_SERVER_CERTIFICATE: $([Environment]::GetEnvironmentVariable('DB_TRUST_SERVER_CERTIFICATE', 'User'))"
Write-Host "DB_TRUSTED_CONNECTION: $([Environment]::GetEnvironmentVariable('DB_TRUSTED_CONNECTION', 'User'))"
Write-Host "DB_MULTIPLE_ACTIVE_RESULT_SETS: $([Environment]::GetEnvironmentVariable('DB_MULTIPLE_ACTIVE_RESULT_SETS', 'User'))"